name: Trigger auto deployment for ai-service

on:
  # Tự chạy khi push lên nhánh main
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/ai-service-AutoDeployTrigger-206db7f6-7643-4127-870e-3d2118aa52e5.yml'

  # Cho phép chạy tay trong tab Actions
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write          # cần cho OIDC login Azure
      contents: read           # cần để checkout code

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AISERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AISERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AISERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build, push image and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          # Source code
          appSourcePath: ${{ github.workspace }}

          # Docker registry: Docker Hub
          registryUrl: docker.io
          registryUsername: ${{ secrets.AISERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AISERVICE_REGISTRY_PASSWORD }}

          # Azure Container App info
          containerAppName: ai-service
          resourceGroup: AIDefCom

          # Image name + tag theo commit
          imageToBuild: hitech2605/ai-service:${{ github.sha }}

          




